# Generated by Django 5.2.10 on 2026-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='drop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
