# Generated by Django 5.2.10 on 2026-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transport', '0002_child_drop_time_child_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
